spring:
  application:
    name: server-discover

server:
  port: 36000
  servlet:
    context-path: /

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:36000/eureka/