server:
  port: 37005

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: ontology
          uri: http://localhost:36002/ontology
          predicates:
            - Path=/api/ontology/**
          filters:
            - StripPrefix=1
        - id: ontology-rule-executor
          uri: http://localhost:36010/rule-executor
          predicates:
            - Path=/api/rule-executor/**
          filters:
            - StripPrefix=1
#      routes:
#        - id: ontology
#          uri: lb://ontology
#          predicates:
#            - Path=/api/ontology/**
#          filters:
#            - StripPrefix=1
knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      version: openapi3
      enabled: true
#eureka:
#  instance:
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 30
#    secure-port-enabled: false
#    non-secure-port-enabled: true
#  client:
#    register-with-eureka: true
#    registry-fetch-interval-seconds: 5
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:36000/eureka/