server:
  port: 37002
  servlet:
    context-path: /ontology

spring:
  application:
    name: ontology
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      #url: jdbc:postgresql://${PG_DB_HOST}:${PG_DB_PORT}/${PG_DB_NAME}?currentSchema=ontology
      url: jdbc:postgresql://192.168.9.11:35432/postgres?currentSchema=ontology&rewriteBatchedStatements=true
      username: iecas
      password: iecas123
      validation-query: SELECT 1
      test-on-borrow: true
    datalake:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.9.11:35432/foudry_datasource
      username: iecas
      password: iecas123

#mybatis:
#  configuration:
#    lazy-loading-enabled: true
#    aggressive-lazy-loading: false
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath*:/mybatis-mapper/*Mapper.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false


#eureka:
#  instance:
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 30
#    secure-port-enabled: false
#    non-secure-port-enabled: true
#  client:
#    register-with-eureka: true
#    registry-fetch-interval-seconds: 5
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:36000/eureka/

ontology:
  swagger:
    enable: true

elasticsearch:
  addr: 192.168.9.101:9200

entity:
  table-url:
    create: "http://192.168.9.11:8088/api/postgres/tables"
    delete: "http://192.168.9.11:8088/api/postgres/tables/{table_name}"
    exist: "http://192.168.9.11:8088/api/postgres/tables/{table_name}/exists"
    count: "http://192.168.9.11:8088/api/postgres/tables/{table_name}/count"
    batch: "http://192.168.9.11:8088/api/postgres/tables/{table_name}/batch"
  node-url:
    create: "http://192.168.9.11:8088/api/ontology/nodes"
    delete: "http://192.168.9.11:8088/api/ontology/nodes/{node_id}"
    exist: "http://192.168.9.11:8088/api/ontology/nodes/{node_id}"
    batch: "http://192.168.9.11:8088/api/ontology/nodes/batch"

# 调其他服务的接口配置
client:
  entity:
    url-prefix: "http://127.0.0.1:37004/ontology_entity"
    create-table:  "/table"
    delete-table: "/table/%s"
    add-column: "/table/column"
    delete-column: "/table/column"
    update-column-relation: "/table/column_relation"