server:
  port: 37002
  servlet:
    context-path: /ontology

spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: ontology
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1024MB
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      #url: jdbc:postgresql://${PG_DB_HOST}:${PG_DB_PORT}/${PG_DB_NAME}?currentSchema=ontology
      url: jdbc:postgresql://192.168.9.11:35432/postgres?currentSchema=ontology&rewriteBatchedStatements=true&TimeZone=UTC
      username: iecas
      password: iecas123
      validation-query: SELECT 1
      test-on-borrow: true
    datalake:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.9.11:35432/entity_datasource
      username: iecas
      password: iecas123
    arangodb:
      host: 192.168.9.11
      port: 8529
      database: entity
      collections: node,relation
      user: root
      password: root
      connections:
        max: 8
        ttl: 1800
      timeout:
        connect: 5000
        request: 10000
  rabbitmq:
    host: 192.168.9.11
    port: 5672
    username: admin
    password: admin
    virtual-host: /


rabbitmq:
  exchange: entity.schema.exchange
  queue: entity.schema.queue
  routing-key: entity.schema


#eureka:
#  instance:
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 30
#    secure-port-enabled: false
#    non-secure-port-enabled: true
#  client:
#    register-with-eureka: true
#    registry-fetch-interval-seconds: 5
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:36000/eureka/

ontology:
  swagger:
    enable: true


#elasticsearch:
#  addr: 192.168.9.101:9200



minio:
  endpoint: http://192.168.9.11:16337
  accessKey: root
  secretKey: iecas123
  bucketName: ptr


orekit:
  data:
    path: "ontology/ontology-server/src/main/resources/orekit-data"

#logging:
#  level:
#    com.arangodb: DEBUG


xxl:
  job:
    baseUrl: http://192.168.9.11:18888/xxl-job-admin
    admin:
      addresses: ${xxl.job.baseUrl}
      addJobUrl:  ${xxl.job.baseUrl}/jobinfo/add
      queryJobExecutorUrl: ${xxl.job.baseUrl}/jobgroup/pageList
      queryJobInfoUrl: ${xxl.job.baseUrl}/jobinfo/pageList
      updateJobUrl: ${xxl.job.baseUrl}/jobinfo/update
      removeJobUrl: ${xxl.job.baseUrl}/jobinfo/remove
      startJobUrl: ${xxl.job.baseUrl}/jobinfo/start
      stopJobUrl: ${xxl.job.baseUrl}/jobinfo/stop
    accessToken: iecas123
    cookie: XXL_JOB_LOGIN_IDENTITY=7b226964223a312c22757365726e616d65223a2261646d696e222c2270617373776f7264223a226531306164633339343962613539616262653536653035376632306638383365222c22726f6c65223a312c227065726d697373696f6e223a6e756c6c7d
    executor:
      appname: ontology-xxl-job-executor
      address:
      ip: 192.168.53.18
      port: 9999
      logpath: ./logs/xxl-job/jobhandler
      logretentiondays: 30


license:
  enable: false
  licensePath: "D:\\ideaProjects\\license.lic"
  publicKeyStorePath: "/publicCerts.keystore"
  storePass: iecas123
  alias: publiccert
  subject: aircas


