server:
  port: 37002
  servlet:
    context-path: /ontology

spring:
  application:
    name: ontology
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1024MB
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      #url: jdbc:postgresql://${PG_DB_HOST}:${PG_DB_PORT}/${PG_DB_NAME}?currentSchema=ontology
      url: jdbc:postgresql://192.168.9.11:35432/postgres?currentSchema=ontology&rewriteBatchedStatements=true&TimeZone=UTC
      username: iecas
      password: iecas123
      validation-query: SELECT 1
      test-on-borrow: true
    datalake:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.9.11:35432/entity_datasource
      username: iecas
      password: iecas123
    arangodb:
      host: 192.168.9.11
      port: 8529
      database: entity
      collections: node,relation
      user: root
      password: root
      connections:
        max: 8
        ttl: 1800
      timeout:
        connect: 5000
        request: 10000




#eureka:
#  instance:
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 30
#    secure-port-enabled: false
#    non-secure-port-enabled: true
#  client:
#    register-with-eureka: true
#    registry-fetch-interval-seconds: 5
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:36000/eureka/

ontology:
  swagger:
    enable: true

#elasticsearch:
#  addr: 192.168.9.101:9200



minio:
  endpoint: http://192.168.9.11:16337
  accessKey: root
  secretKey: iecas123
  bucketName: ptr