server:
  port: 37004
  servlet:
    context-path: /ontology_entity

spring:
  # ArangoDB配置
  data:
    arangodb:
      host: 192.168.9.11
      port: 8529
      database: entity
      collections: node,relation
      user: root
      password: root
      connections:
        max: 8
        ttl: 1800
      timeout:
        connect: 5000
        request: 10000

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # PostgreSQL配置
  datasource:
    main:
      url: jdbc:postgresql://192.168.9.11:35432/postgres?currentSchema=ontology_entity&rewriteBatchedStatements=true
      username: postgres
      password: iecas123
      driver-class-name: org.postgresql.Driver
    datalake:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.9.11:35432/foudry_datasource?currentSchema=public
      username: iecas
      password: iecas123

# 日志配置
logging:
  level:
    org.springframework.data.arangodb: INFO
    org.springframework.jdbc: DEBUG
    com.example.ontology: DEBUG

springfox:
  documentation:
    swagger-ui:
      enabled: true
    enabled: true
