server:
  port: 36010
  servlet:
    context-path: /ontology-api

spring:
  application:
    name: ontology-api-service
  datasource:
    driver-class-name: org.postgresql.Driver
      #url: jdbc:postgresql://${PG_DB_HOST}:${PG_DB_PORT}/${PG_DB_NAME}?currentSchema=ontology
    url: jdbc:postgresql://192.168.9.17:35432/postgres?currentSchema=ontology_api
    username: iecas
    password: iecas123
    validation-query: SELECT 1
    test-on-borrow: true


ontology:
  swagger:
    enable: true
  # ontoloogy 服务地址
  server: http://${ONTOLOGY_SERVER}:36002/ontology

