package com.aircas.ptr.foundry.ontology.service.impl;

import com.aircas.ptr.foundry.common.util.PreconditionUtils;
import com.aircas.ptr.foundry.ontology.context.UserContextHolder;
import com.aircas.ptr.foundry.ontology.model.dto.ActionContextInfoDTO;
import com.aircas.ptr.foundry.ontology.model.dto.FunctionParamDTO;
import com.aircas.ptr.foundry.ontology.model.enums.*;
import com.aircas.ptr.foundry.ontology.model.param.*;
import com.aircas.ptr.foundry.ontology.model.po.*;
import com.aircas.ptr.foundry.ontology.model.vo.*;
import com.aircas.ptr.foundry.ontology.repository.mainMapper.*;
import com.aircas.ptr.foundry.ontology.service.*;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.conditions.update.LambdaUpdateWrapper;
import com.baomidou.mybatisplus.core.metadata.OrderItem;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.annotation.Resource;
import lombok.RequiredArgsConstructor;
import lombok.SneakyThrows;
import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang3.StringUtils;
import org.springframework.context.annotation.Lazy;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.util.stream.Collectors;

@Service @RequiredArgsConstructor
public class FunctionServiceImpl extends ServiceImpl<FunctionMapper, Function> implements FunctionService {
 @Resource private OntologyActionMapper ontologyActionMapper;
 @Resource private FunctionExecuteResultMapper executeResultMapper;
 @Resource private FunctionVersionMapper functionVersionMapper;
 @Resource private FunctionParamService functionParamService;
 @Resource private GroovyService groovyService;
 @Lazy @Resource private EntityServiceImpl entityService;
 private final ObjectMapper objectMapper = new ObjectMapper();

 public FunctionDetailVO getFunctionDetailByApi(String api){return getFunctionDetailByApi(api,null);}
 public FunctionDetailVO getFunctionDetailByApi(String api,Integer no){Function f=requireFunction(api); FunctionVersion v=no==null?requirePublished(f):requireVersion(f,no); return detail(f,v);}
 private FunctionDetailVO detail(Function f,FunctionVersion v){List<FunctionParameterVO> ps=functionParamService.list(new LambdaQueryWrapper<FunctionParamPO>().eq(FunctionParamPO::getFunctionVersionId,v.getId()).orderByAsc(FunctionParamPO::getParamOrder)).stream().map(p->FunctionParameterVO.builder().paramId(p.getId()).paramName(p.getParamName()).category(p.getCategory()).paramOrder(p.getParamOrder()).paramSchema(p.getParamSchema()).paramType(p.getParamType()).description(p.getDescription()).build()).collect(Collectors.toList()); return FunctionDetailVO.builder().functionApi(f.getApi()).displayName(f.getDisplayName()).description(f.getDescription()).type(f.getType()).model(f.getModel()).code(v.getCode()).referenceName(v.getReferenceName()).params(ps).versionId(v.getId()).versionNo(v.getVersionNo()).versionStatus(v.getVersionStatus()).build();}

 @Transactional(value="mainTransactionManager") public void deleteByApi(String api){Function f=requireFunction(api); Long n=ontologyActionMapper.selectCount(new LambdaQueryWrapper<OntologyAction>().eq(OntologyAction::getFunctionApi,api)); PreconditionUtils.checkArgument(n==0,"该函数已被行为关联: "+api,HttpStatus.BAD_REQUEST); f.setStatus(Status.DELETE.getValue()); updateById(f);}
 @Transactional(value="mainTransactionManager") public void createFunction(FunctionCreateParam p){PreconditionUtils.checkArgument(getOne(new LambdaQueryWrapper<Function>().eq(Function::getApi,p.getFunctionApi()))==null,"函数api已存在:"+p.getFunctionApi(),HttpStatus.BAD_REQUEST); Function f=Function.builder().api(p.getFunctionApi()).description(p.getDescription()).displayName(p.getDisplayName()).type(p.getType()).model(p.getModel()).status(Status.ENABLE.getValue()).latestVersionNo(1).build(); save(f); FunctionVersion v=newVersion(f,1,p.getCode(),p.getReferenceName(),p.getChangeLog()); functionVersionMapper.insert(v); insertParams(f.getId(),v,f.getType()); if(Boolean.TRUE.equals(p.getPublish()))publish(f,v);}
 @Transactional(value="mainTransactionManager") public void updateFunction(FunctionUpdateParam p){Function f=requireFunction(p.getFunctionApi()); f.setDisplayName(p.getDisplayName()).setDescription(p.getDescription()); updateById(f); FunctionVersion v=findDraft(f.getId()); if(v==null){v=newVersion(f,allocate(f),p.getCode(),p.getReferenceName(),p.getChangeLog()); functionVersionMapper.insert(v);}else{v.setCode(p.getCode()).setReferenceName(p.getReferenceName()).setChangeLog(p.getChangeLog()); functionVersionMapper.updateById(v); functionParamService.remove(new LambdaQueryWrapper<FunctionParamPO>().eq(FunctionParamPO::getFunctionVersionId,v.getId()));} insertParams(f.getId(),v,f.getType());}
 @Transactional(value="mainTransactionManager") public void createDraft(FunctionVersionParam p){Function f=requireFunction(p.getFunctionApi()); PreconditionUtils.checkArgument(findDraft(f.getId())==null,"该函数已存在草稿",HttpStatus.BAD_REQUEST); FunctionVersion s=f.getPublishedVersionId()==null?null:functionVersionMapper.selectById(f.getPublishedVersionId()); FunctionVersion v=newVersion(f,allocate(f),p.getCode()!=null?p.getCode():s==null?null:s.getCode(),p.getReferenceName()!=null?p.getReferenceName():s==null?null:s.getReferenceName(),p.getChangeLog()); functionVersionMapper.insert(v); insertParams(f.getId(),v,f.getType());}
 @Transactional(value="mainTransactionManager") public void publishVersion(FunctionVersionParam p){Function f=requireFunction(p.getFunctionApi()); publish(f,requireVersion(f,p.getVersionNo()));}
 private void publish(Function f,FunctionVersion v){PreconditionUtils.checkArgument(v.getVersionStatus()==FunctionVersionStatusEnum.DRAFT,"只能发布草稿版本",HttpStatus.BAD_REQUEST); if(f.getType()==FunctionTypeEnum.CUSTOMIZE)groovyService.parseGroovyCode(v.getCode()); else PreconditionUtils.checkArgument(StringUtils.isNotBlank(v.getReferenceName()),"外部函数引用不能为空",HttpStatus.BAD_REQUEST); if(f.getPublishedVersionId()!=null)functionVersionMapper.update(null,new LambdaUpdateWrapper<FunctionVersion>().eq(FunctionVersion::getId,f.getPublishedVersionId()).set(FunctionVersion::getVersionStatus,FunctionVersionStatusEnum.DEPRECATED)); v.setVersionStatus(FunctionVersionStatusEnum.PUBLISHED).setPublishTime(new Date()); functionVersionMapper.updateById(v); f.setPublishedVersionId(v.getId()).setPublishedVersionNo(v.getVersionNo()); updateById(f);}
 @Transactional(value="mainTransactionManager") public void rollbackVersion(FunctionVersionParam p){Function f=requireFunction(p.getFunctionApi()); FunctionVersion s=requireVersion(f,p.getVersionNo()); PreconditionUtils.checkArgument(s.getVersionStatus()!=FunctionVersionStatusEnum.DRAFT,"不能回滚到草稿",HttpStatus.BAD_REQUEST); FunctionVersion v=newVersion(f,allocate(f),s.getCode(),s.getReferenceName(),p.getChangeLog()); functionVersionMapper.insert(v); copyParams(f.getId(),s.getId(),v); publish(f,v);}
 public Page<FunctionVersionVO> listVersions(String api,Integer pn,Integer ps){Function f=requireFunction(api); Page<FunctionVersion> p=functionVersionMapper.selectPage(new Page<FunctionVersion>(pn,ps).addOrder(OrderItem.desc("version_no")),new LambdaQueryWrapper<FunctionVersion>().eq(FunctionVersion::getFunctionId,f.getId())); List<FunctionVersionVO> rs=p.getRecords().stream().map(v->FunctionVersionVO.builder().versionId(v.getId()).functionApi(v.getFunctionApi()).versionNo(v.getVersionNo()).versionStatus(v.getVersionStatus()).changeLog(v.getChangeLog()).createBy(v.getCreateBy()).publishTime(v.getPublishTime()).createTime(v.getCreateTime()).build()).collect(Collectors.toList()); return new Page<FunctionVersionVO>(pn,ps).setTotal(p.getTotal()).setRecords(rs);}
 public Page<FunctionInfoVO> getFunctions(Integer pn,Integer ps){Page<Function> p=page(new Page<Function>(pn,ps).addOrder(OrderItem.desc("create_time")),new LambdaQueryWrapper<Function>().ne(Function::getStatus,Status.DELETE.getValue())); List<FunctionInfoVO> rs=p.getRecords().stream().map(f->{FunctionVersion d=findDraft(f.getId());return FunctionInfoVO.builder().functionApi(f.getApi()).displayName(f.getDisplayName()).type(f.getType()).model(f.getModel()).description(f.getDescription()).publishedVersionNo(f.getPublishedVersionNo()).draftVersionNo(d==null?null:d.getVersionNo()).hasDraft(d!=null).build();}).collect(Collectors.toList()); return new Page<FunctionInfoVO>(pn,ps).setTotal(p.getTotal()).setRecords(rs);}

 @SneakyThrows public String executeFunction(FunctionExecuteParam p){Function f=requireFunction(p.getFunctionApi()); FunctionVersion v=p.getVersionNo()==null?requirePublished(f):requireVersion(f,p.getVersionNo()); PreconditionUtils.checkArgument(v.getVersionStatus()!=FunctionVersionStatusEnum.DRAFT,"正式执行接口不允许执行草稿",HttpStatus.BAD_REQUEST); List<FunctionParamPO> in=functionParamService.list(new LambdaQueryWrapper<FunctionParamPO>().eq(FunctionParamPO::getFunctionVersionId,v.getId()).eq(FunctionParamPO::getCategory,FunctionParamCategoryEnum.INPUT).orderByAsc(FunctionParamPO::getParamOrder)); Map<String,Object> vals=CollectionUtils.isEmpty(p.getParameters())?new HashMap<>():p.getParameters().stream().collect(HashMap::new,(m,x)->m.put(x.getParamName(),x.getParamValue()),HashMap::putAll); String json=groovyService.executeGroovy(v.getId(),f.getApi(),v.getCode(),vals,in); FunctionResultVO r=objectMapper.readValue(json,new TypeReference<FunctionResultVO>(){}); if(r!=null&&StringUtils.isNotEmpty(r.getTaskId()))executeResultMapper.insert(FunctionExecuteResult.builder().taskId(r.getTaskId()).functionApi(f.getApi()).functionVersionId(v.getId()).functionVersionNo(v.getVersionNo()).functionParam(objectMapper.writeValueAsString(p.getParameters())).taskStatus(TaskStatusEnum.PENDING).build()); return json;}
 @SneakyThrows public FunctionExecuteResultVO getExecuteResult(String id){FunctionExecuteResult r=executeResultMapper.selectOne(new LambdaQueryWrapper<FunctionExecuteResult>().eq(FunctionExecuteResult::getTaskId,id)); if(r==null)return null; return FunctionExecuteResultVO.builder().taskId(r.getTaskId()).functionApi(r.getFunctionApi()).functionVersionId(r.getFunctionVersionId()).functionVersionNo(r.getFunctionVersionNo()).actionApi(r.getActionApi()).functionParam(r.getFunctionParam()).taskStatus(r.getTaskStatus()).result(StringUtils.isEmpty(r.getResult())?null:objectMapper.readValue(r.getResult(),new TypeReference<FunctionResultVO>(){})).build();}
 @SneakyThrows @Transactional(value="mainTransactionManager") public void callback(FunctionResultVO result){FunctionExecuteResult r=executeResultMapper.selectOne(new LambdaQueryWrapper<FunctionExecuteResult>().eq(FunctionExecuteResult::getTaskId,result.getTaskId()).eq(FunctionExecuteResult::getTaskStatus,TaskStatusEnum.PENDING)); PreconditionUtils.checkNotNull(r,"task id 不存在或已完成："+result.getTaskId()); if(StringUtils.isNotEmpty(r.getActionApi())&&StringUtils.isNotEmpty(r.getActionContextInfo()))entityService.updateEntityPropertyAndRelation(objectMapper.writeValueAsString(result),objectMapper.readValue(r.getActionContextInfo(),new TypeReference<ActionContextInfoDTO>(){})); r.setTaskStatus(TaskStatusEnum.COMPLETED).setResult(objectMapper.writeValueAsString(result)); executeResultMapper.updateById(r);}

 private Function requireFunction(String api){Function f=getOne(new LambdaQueryWrapper<Function>().eq(Function::getApi,api).ne(Function::getStatus,Status.DELETE.getValue())); PreconditionUtils.checkArgument(f!=null,"函数api不存在："+api,HttpStatus.BAD_REQUEST); return f;}
 private FunctionVersion requirePublished(Function f){PreconditionUtils.checkArgument(f.getPublishedVersionId()!=null,"函数无已发布版本: "+f.getApi(),HttpStatus.BAD_REQUEST); FunctionVersion v=functionVersionMapper.selectById(f.getPublishedVersionId()); PreconditionUtils.checkArgument(v!=null&&v.getFunctionId().equals(f.getId())&&v.getVersionStatus()==FunctionVersionStatusEnum.PUBLISHED,"函数发布指针无效: "+f.getApi(),HttpStatus.BAD_REQUEST); return v;}
 private FunctionVersion requireVersion(Function f,Integer no){PreconditionUtils.checkNotNull(no,"versionNo不能为空"); FunctionVersion v=functionVersionMapper.selectOne(new LambdaQueryWrapper<FunctionVersion>().eq(FunctionVersion::getFunctionId,f.getId()).eq(FunctionVersion::getVersionNo,no)); PreconditionUtils.checkArgument(v!=null,"函数版本不存在: "+f.getApi()+"#"+no,HttpStatus.BAD_REQUEST); return v;}
 private FunctionVersion findDraft(Long id){return functionVersionMapper.selectOne(new LambdaQueryWrapper<FunctionVersion>().eq(FunctionVersion::getFunctionId,id).eq(FunctionVersion::getVersionStatus,FunctionVersionStatusEnum.DRAFT));}
 private int allocate(Function f){for(int i=0;i<5;i++){int n=f.getLatestVersionNo()==null?0:f.getLatestVersionNo();int changed=baseMapper.update(null,new LambdaUpdateWrapper<Function>().eq(Function::getId,f.getId()).eq(Function::getLatestVersionNo,n).set(Function::getLatestVersionNo,n+1));if(changed==1){f.setLatestVersionNo(n+1);return n+1;}f=baseMapper.selectById(f.getId());}throw new IllegalStateException("函数版本号分配冲突，请重试");}
 private FunctionVersion newVersion(Function f,int no,String code,String ref,String log){String user=UserContextHolder.get()==null?null:UserContextHolder.get().getUsername();return FunctionVersion.builder().functionId(f.getId()).functionApi(f.getApi()).versionNo(no).code(code).referenceName(ref).versionStatus(FunctionVersionStatusEnum.DRAFT).changeLog(log).createBy(user).build();}
 private void insertParams(Long fid,FunctionVersion v,FunctionTypeEnum type){if(type!=FunctionTypeEnum.CUSTOMIZE)return;List<FunctionParamDTO> parsed=groovyService.parseGroovyCode(v.getCode());if(CollectionUtils.isEmpty(parsed))return;functionParamService.saveBatch(parsed.stream().map(p->FunctionParamPO.builder().functionId(fid).functionVersionId(v.getId()).functionVersionNo(v.getVersionNo()).paramName(p.getParamName()).paramType(p.getParamType()).category(p.getCategory()).paramSchema(p.getParamSchema()).paramOrder(p.getParamOrder()).typeReferenceName(p.getReferenceType()).createTime(new Date()).updateTime(new Date()).build()).collect(Collectors.toList()));}
 private void copyParams(Long fid,Long source,FunctionVersion v){List<FunctionParamPO> ps=functionParamService.list(new LambdaQueryWrapper<FunctionParamPO>().eq(FunctionParamPO::getFunctionVersionId,source));functionParamService.saveBatch(ps.stream().map(p->FunctionParamPO.builder().functionId(fid).functionVersionId(v.getId()).functionVersionNo(v.getVersionNo()).paramName(p.getParamName()).paramType(p.getParamType()).category(p.getCategory()).paramSchema(p.getParamSchema()).paramOrder(p.getParamOrder()).description(p.getDescription()).typeReferenceName(p.getTypeReferenceName()).build()).collect(Collectors.toList()));}
}
